import { Router } from 'express';
import authRoutes from './auth.routes';
import customerRoutes from './customer.routes';
import customerAddressHistoryRoutes from './customer-address-history.routes';
import debtManagementRoutes from './debt-management.route';
import debtRoutes from './debt.routes';
import deliveryRoutes from './delivery.routes';
import draftDeliveryRoutes from './draft-delivery.routes';
import moneyDeliveryRoutes from './money-delivery.routes';
import routeRoutes from './route.routes';
import settingsRoutes from './settings.routes';
import testRoutes from './test.routes';
import userRouteRoutes from './user-route.routes';
import userRoutes from './user.route';
import returnDeliveriesRoutes from './return-deliveries.route';
import returnMoneyDeliveriesRoutes from './return-money-deliveries.route';
import reportRoutes from './report.routes';
import smsNotificationRoutes from './sms-notification.routes';
import shipmentLogRoutes from './shipment-log.routes';
import homeDeliveryPriceRoutes from './home-delivery-price.routes';
import homeDeliveryCalculatorRoutes from './home-delivery-calculator.routes';
import vietQrRoutes from './vietqr.routes';

const router = Router();

router.use('/test', testRoutes);
router.use('/auth', authRoutes);
router.use('/customer', customerRoutes);
router.use('/customer-address-history', customerAddressHistoryRoutes);
router.use('/delivery', deliveryRoutes);
router.use('/money-deliveries', moneyDeliveryRoutes);
router.use('/route', routeRoutes);
router.use('/user-route', userRouteRoutes);
router.use('/user', userRoutes);
router.use('/settings', settingsRoutes);
router.use('/draft-deliveries', draftDeliveryRoutes);
router.use('/debt-management', debtManagementRoutes);
router.use('/debt', debtRoutes);
router.use('/return-deliveries', returnDeliveriesRoutes);
router.use('/return-money-deliveries', returnMoneyDeliveriesRoutes);
router.use('/report', reportRoutes);
router.use('/sms', smsNotificationRoutes);
router.use('/shipment-logs', shipmentLogRoutes);
router.use('/home-delivery-prices', homeDeliveryPriceRoutes);
router.use('/home-delivery-calculator', homeDeliveryCalculatorRoutes);
router.use('/vietqr', vietQrRoutes);

export default router;
